development:
  adapter: postgresql
  database: media_dev
  username: Andrey
  password: rfhjcnf
  host: localhost

test:
  adapter: postgresql
  database: media_test
  username: Andrey
  password: rfhjcnf
  host: localhost
