development:
  adapter: postgresql
  database: media_dev
  username: pguser
  password: pguser
  host: localhost

test:
  adapter: postgresql
  database: media_test
  username: pguser
  password: pguser
  host: localhost
