# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 811bb77d1d59aa049aea24c0dae4d112351e958471a77cfab6908752f7afb6b72df88ea1ff732d51f7731a537a3e2b443e1f185b8d0782542bbc965c22e42f16

test:
  secret_key_base: e66f4412f413c6eb0f1f53ca63874c4d4c4f436cbf877df83756f39363882531fec2d5087391ebea98a71aaa11af90885266684b95a4fe86b0172f62c3ef8519

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
